spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db1?serverTimezone=UTC
    username: root
    password: root1
    type: com.alibaba.druid.pool.DruidDataSource
#  mp日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    # dao中的id自增
    db-config:
      id-type: auto     # 确定表里也是自增，
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
