server:
  port: 8080
spring:
  application:
    name: reggie_take_out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: root1
      type: com.alibaba.druid.pool.DruidDataSource

  redis:
    host: localhost
    port: 6379
    # password:123456
    database: 0  #操作的是0号数据库
mybatis-plus:
  configuration:
    #address_book------>AddressBook
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true #开启这里的内容，可以用mybatis-plus来进行表和类名进行映射关系，比如address_book------>AddressBook
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

reggie:
  path: D:\img\

